select * from users;
select email, name   from users;
select * from users where gender ="Male";
select * from users where date_of_birth is not null;
select * from users where date_of_birth between "1992-01-01" and "1995-12-12";
select * from users where date_of_birth != "1990-11-23";
select * from users where date_of_birth< "1991-01-01";
select * from users where date_of_birth = "1990-11-23";
select * from users where salary in (65000, 58000);
select * from users;
select * from users where gender ="male" and salary > 80000;
select * from users where gender ="female" and salary > 75000 order by salary desc limit 1;
update users set salary="70000" where id=5;
select * from users;
  -- set sql_safe_updates =0;
update users set salary = salary + 5000;
select * from users;
update users set name = "Ayesha Khan" where id = 7; 
select * from users;
select * from users where salary <= 60000;
update users set salary = salary + 10000 where salary <=60000;
select * from users;
update users set salary = 50000;
select * from users;
delete from users where salary <51000;
select* from users;
alter table users drop column email;
alter table users add column email varchar(100) not null;
select * from users;
alter table users add constraint unique_email unique(email);
describe users;